title: Food.  Family.  Technology.  Life.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.01772286
  brandStrength: 0.9446831
  lightness: 0
  brandColors:
    - '#0C0603'
    - '#88421F'
    - '#4C1E0D'
    - '#B56D43'
    - '#DFB592'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Fat Boy Heaven
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.829753
layout_spectrum: 0.1348013
