title: Food.  Family.  Technology.  Life.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.01772286
  brandStrength: 0.005751868
  lightness: 0
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Fat Boy Heaven
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.829753
layout_spectrum: 0.1348013
