layout_spectrum: 0.6460795
color:
  saturation: 0.4301826
  brandStrength: 0.005751868
  lightness: 0.5515575
  rhythmicContrast: 0.1895811
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.7438238
name: Fat Boy Heaven
